"""Auto-PR: render suggestion as branch + commit + PR with evidence."""
from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path

from ccpilot.analyze import build_analysis
from ccpilot.rules import run_all
from ccpilot.types import Suggestion


def _suggestion_to_diff(s: Suggestion, repo: Path) -> str:
    """Produce a textual change for the suggestion. Falls back to a Markdown note."""
    if s.kind == "claude-md-rule":
        target = repo / "CLAUDE.md"
        if not target.exists():
            return ""
        text = target.read_text()
        replacements = [
            ("You should ", "MUST "),
            ("you should ", "must "),
            ("Try to ", "MUST "),
            ("try to ", "must "),
            ("Usually ", ""),
            ("usually ", ""),
            ("Typically ", ""),
            ("typically ", ""),
        ]
        new = text
        for a, b in replacements:
            new = new.replace(a, b)
        if new == text:
            return ""
        target.write_text(new)
        return "modified CLAUDE.md (hedging removed)"
    # Default: emit ccpilot-notes.md
    notes = repo / "ccpilot-notes.md"
    if notes.exists():
        cur = notes.read_text()
    else:
        cur = "# ccpilot suggestions\n\n"
    body = (
        f"\n## {s.kind}: {s.target}\n\n"
        f"- confidence: {s.confidence:.0%}\n"
        f"- est. savings: ${s.estimated_savings_usd_month:.2f}/mo\n"
        f"- evidence: `{json.dumps(s.evidence, default=str)}`\n\n"
        f"{s.rationale}\n"
    )
    notes.write_text(cur + body)
    return "appended ccpilot-notes.md"


def open_pr_from_suggestion(
    repo: Path,
    *,
    suggestion_id: str,
    dry_run: bool = True,
) -> int:
    if not (repo / ".git").exists():
        print(f"not a git repo: {repo}", file=sys.stderr)
        return 2

    claude_md = repo / "CLAUDE.md"
    a = build_analysis(window_days=30, claude_md_path=claude_md if claude_md.exists() else None)
    suggestions = {s.id: s for s in run_all(a)}
    s = suggestions.get(suggestion_id)
    if not s:
        print(f"suggestion '{suggestion_id}' not found. Available:")
        for sid in suggestions:
            print(f"  {sid}")
        return 1

    branch = f"ccpilot/{s.id.replace(':', '-')}"
    body_md = (
        f"## CCPilot suggestion: {s.kind}\n\n"
        f"**Target:** `{s.target}`\n"
        f"**Confidence:** {s.confidence:.0%}\n"
        f"**Est. savings:** ${s.estimated_savings_usd_month:.2f}/month\n\n"
        f"### Rationale\n\n{s.rationale}\n\n"
        f"### Evidence\n\n```json\n{json.dumps(s.evidence, indent=2, default=str)}\n```\n\n"
        f"---\n_Generated by [ccpilot](https://github.com/ao92265/claude-observatory)._\n"
    )

    if dry_run:
        print(f"\n[DRY RUN] Would create branch '{branch}' and PR:\n")
        print("=" * 60)
        print(body_md)
        print("=" * 60)
        print(f"\nRun with --apply to push + open PR via gh.")
        return 0

    # Live mode
    if not shutil.which("gh"):
        print("gh CLI not installed", file=sys.stderr)
        return 2

    def git(*args: str) -> subprocess.CompletedProcess:
        return subprocess.run(["git", *args], cwd=str(repo), capture_output=True, text=True)

    current = git("branch", "--show-current").stdout.strip() or "main"
    r = git("checkout", "-b", branch)
    if r.returncode != 0:
        print(f"checkout failed: {r.stderr}", file=sys.stderr)
        return 1
    note = _suggestion_to_diff(s, repo)
    if not note:
        git("checkout", current)
        git("branch", "-D", branch)
        print("no diff generated — suggestion not actionable in this repo")
        return 1
    git("add", "-A")
    git("commit", "-m", f"ccpilot: {s.kind} — {s.target}\n\n{s.rationale}")
    push = git("push", "-u", "origin", branch)
    if push.returncode != 0:
        print(f"push failed: {push.stderr}", file=sys.stderr)
        return 1
    pr = subprocess.run(
        ["gh", "pr", "create", "--title", f"ccpilot: {s.kind}", "--body", body_md],
        cwd=str(repo),
        capture_output=True,
        text=True,
    )
    print(pr.stdout)
    if pr.returncode != 0:
        print(pr.stderr, file=sys.stderr)
        return pr.returncode
    return 0
